version: "3"
services:
  hub:
    image: selenium/hub:3.141.5-astatine
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=15
      - GRID_NEW_SESSION_WAIT_TIMEOUT=30000
      - GRID_DEBUG=true
      - GRID_CLEAN_UP_CYCLE=5000
      - GRID_BROWSER_TIMEOUT=240
      
  chrome-v.70:
    image: selenium/node-chrome:3.141.5-astatine
    shm_size: 2G
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  chrome-v.69:
    image: selenium/node-chrome:3.14.0-helium
    shm_size: 2G
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  firefox-v.63:
    image: selenium/node-firefox:3.141.5-astatine
    shm_size: 2G
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  firefox-v.62:
    image: selenium/node-firefox:3.14.0-helium
    shm_size: 2G
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  tests:
    build:
      context: ./
    depends_on:
      - chrome-v.70
      - chrome-v.69
      - firefox-v.62
      - firefox-v.63
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    
