version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.14.0-beryllium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14.0-beryllium
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.14.0-beryllium
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  
  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /tmp/autotests/reports:/usr/src/app/reports
    depends_on:
      - selenium-hub
      - chrome
    environment:
      SELENIUM_HUB_HOST: selenium-hub
      SELENIUM_HUB_PORT: 4444
      CONCURRENCY: $CONCURRENCY
      URL: $URL
