version: "3"
services:
  hub:
    image: selenium/hub:3.14.0-iron
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.14.0-iron
    shm_size: 2G
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.14.0-iron
    shm_size: 2G
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  tests:
    build:
      context: ./
    depends_on:
      - hub
      - chrome
      - firefox 
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
