version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.14.0-curium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14.0-curium
    links:
      - selenium-hub
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.14.0-curium
    links:
      - selenium-hub
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  # chrome-debug:
  #   image: selenium/node-chrome-debug:3.14.0-curium
  #   ports:
  #     - "4447:4444"
  #   links:
  #     - selenium-hub
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  # firefox-debug:
  #   image: selenium/node-firefox-debug:3.14.0-curium
  #   ports:
  #     - "4448:4444"
  #   links:
  #     - selenium-hub
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444    

  tests:
    links:
    - selenium-hub
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /tmp/autotests/reports:/usr/src/app/reports
    depends_on:
      - selenium-hub
      - firefox
      - chrome
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - CONCURRENCY=$CONCURRENCY
      - URL=$URL
